{"name": "test_03", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 < 1", "trace": "def test_03():\n>       assert 2 < 1\nE       assert 2 < 1\n\ntest_case.py:20: AssertionError"}, "start": 1618048097956, "stop": 1618048097956, "uuid": "7c6454c1-fc33-4d77-a951-ffad4b9c5dea", "historyId": "5c1cb06c1153d91e2e23f5f3ccf9466d", "testCaseId": "772ee26b921bb8752ea8a976ba718c29", "fullName": "test_case#test_03", "labels": [{"name": "suite", "value": "test_case"}, {"name": "host", "value": "DESKTOP-5SVAUJU"}, {"name": "thread", "value": "2960-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case"}]}